import { validate } from 'uuid';
import * as yup from 'yup';

const bcgVaccinationFields = {
  'BCG Vaccine': [
    {
      name: 'batchNumber',
      label: 'Batch number',
      type: 'text',
      required: true,
      visibleFor: [0],
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 6,
      },
      validate: yup.string().required('Batch number is required'),
    },
    {
      name: 'lotNumber',
      label: 'Lot number',
      type: 'text',
      required: true,
      visibleFor: [0],
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 6,
      },
      validate: yup.string().required('Lot number is required'),
    },
    {
      name: 'manufacturer',
      label: 'Manufacturer',
      type: 'text',
      required: true,
      visibleFor: [0],
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 6,
      },
      validate: yup.string().required('Manufacturer is required'),
    },
    {
      name: 'dateOfExpiry',
      label: 'Date of expiry',
      type: 'date',
      required: true,
      visibleFor: [0],
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 6,
      },
      validate: yup.date().required('Date of expiry is required'),
    },
    {
      name: 'bcgDosage',
      label: 'Dose',
      type: 'select',
      required: true,
      visibleFor: [0],
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 6,
      },
      options: [
        { value: '0.05', label: '0.05ml (below 1 year)' },
        { value: '0.1', label: '0.1ml (above 1 year)' },
      ],
      validate: yup.string().required('Dosage is required'),
    },
    {
      name: 'immunizationDateGiven',
      label: 'Date Given',
      type: 'date',
      required: true,
      visibleFor: [0],
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 6,
      },
      validate: yup.date().required('Date given is required'),
    },
    {
      name: 'immunizationDateOfNextVisit',
      label: 'Date of Next Visit (for scar check)',
      type: 'date',
      required: true,
      visibleFor: [0],
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 6,
      },
      validate: yup.date().required('Date of next visit is required'),
    },
    {
      name: 'bcgScarDateChecked',
      label: 'BCG Scar Date Checked',
      type: 'date',
      required: true,
      visibleFor: [1],
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 6,
      },
      validate: yup.date().required('Date checked is required'),
    },
    {
      name: 'bcgScarPresence',
      label: 'BCG Scar',
      type: 'radio',
      options: [
        { value: 'PRESENT', label: 'Present' },
        { value: 'ABSENT', label: 'Absent' },
      ],
      required: true,
      visibleFor: [1],
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 6,
      },
      validate: yup.string().required('BCG scar presence check required'),
    },
    {
      name: 'repeatVaccineBcg',
      label: 'Repeat BCG Vaccine',
      type: 'radio',
      options: [
        { value: 'Yes', label: 'Yes' },
        { value: 'No', label: 'No' },
      ],
      required: true,
      visibleFor: [1],
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 6,
      },
      validate: yup.string().required('Repeat BCG Vaccine required'),
    },

    
  ],
  'Repeat BCG Vaccine': [
    {
      name: 'repeatBatchNumber',
      label: 'Repeat Batch number',
      type: 'text',
      required: true,
      visibleFor: [1],
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 6,
      },
      relevant: formValues => formValues.repeatVaccineBcg === 'Yes',
      validate: yup.string().when('repeatVaccineBcg', {
        is: 'Yes',
        then: yup.string().required('Repeat batch number is required'),
      }),
    },
    {
      name: 'repeatLotNumber',
      label: 'Repeat Lot number',
      type: 'text',
      required: true,
      visibleFor: [1],
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 6,
      },
      relevant: formValues => formValues.repeatVaccineBcg === 'Yes',
      validate: yup.string().when('repeatVaccineBcg', {
        is: 'Yes',
        then: yup.string().required('Repeat lot number is required'),
      }),
    },
    {
      name: 'repeatManufacturer',
      label: 'Repeat Manufacturer',
      type: 'text',
      required: true,
      visibleFor: [1],
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 6,
      },
      relevant: formValues => formValues.repeatVaccineBcg === 'Yes',
      validate: yup.string().when('repeatVaccineBcg', {
        is: 'Yes',
        then: yup.string().required('Repeat manufacturer is required'),
      }),
    },
    {
      name: 'repeatDateOfExpiry',
      label: 'Repeat Date of expiry',
      type: 'date',
      required: true,
      visibleFor: [1], 
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 6,
      },
      relevant: formValues => formValues.repeatVaccineBcg === 'Yes',
      validate: yup.date().when('repeatVaccineBcg', {
        is: 'Yes',
        then: yup.date().required('Repeat date of expiry is required'),
      }),
    },
    {
      name: 'repeatBcgDosage',
      label: 'Dose',
      type: 'select',
      required: true,
      visibleFor: [1],
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 6,
      },
      options: [
        { value: '0.05', label: '0.05ml (below 1 year)' },
        { value: '0.1', label: '0.1ml (above 1 year)' },
      ],
      relevant: formValues => formValues.repeatVaccineBcg === 'Yes',
      validate: yup.string().when('repeatVaccineBcg', {
        is: 'Yes',
        then: yup.string().required('Repeat dosage is required'),
      }),
    },
    {
      name: 'repeatImmunizationDateGiven',
      label: 'Repeat BCG Date',
      type: 'date',
      required: true,
      visibleFor: [1],
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 6,
      },
      relevant: formValues => formValues.repeatVaccineBcg === 'Yes',
      validate: yup.date().when('repeatVaccineBcg', {
        is: 'Yes',
        then: yup.date().required('Repeat BCG date is required'),
      }),
    },
  ],
};

export default bcgVaccinationFields;